name: create 
on:
  # schedule:
  #   - cron: '0 21 * * 2,5' # Run on Tuesday and Friday 9pm UTC (5pm EST)
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

# Cacnel previous runs if a new push is sent
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  create-zip:
    # Don't run if a pull request but not closed
    if: github.event_name == 'schedule' || ((github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == 'true') || github.event_name == 'push')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pages: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}    
    steps:
      # Downloading both the repositories to simulate the original task
      - uses: actions/checkout@main
        with:
          path: ${{ github.event.repository.name }}
      - uses: r-lib/actions/setup-r@v2
      - run: echo "💡 The ${{ github.repository }} repository have been cloned to the runner."
      - name: Set up "data commons environment"
        working-directory: ${{ github.workspace }}/${{ github.event.repository.name }}
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::init()	
          renv::restore()	
          install.packages('remotes')
          remotes::install_github('uva-bi-sdad/community')
          renv::snapshot()
      - name: List files
        run: |
          ls -la
      - name: Commit files # Commit changes. You need to do this so child sites work...
        working-directory: ${{ github.event.repository.name }}
        run: |
          ls -la
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "saving renv"
          git push

